spring:
  application:
    name: authorization-service
  banner:
    location: banner.txt

datasource:
  url: jdbc:mysql://localhost:3306/microdb
  username: root
  password: admin123

eureka:
  client:
    enabled: false